### ISSUE TITLE
Copy on info screens

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#13]
From the campaign: 
On the swipe screens...

· Postbox screen can we change the text below the icon to “Return it to your local authority office by May 5th.”
· Vote Envelope screen – Text above the icon “On May 22nd” text below “Polling stations will be open from 7am to 10pm.”
· Delete away for work and change of address screens
· Final screen (doesn't exist on Android yet, white screen with coloured YES image top text: "And remember..." bottom text: "Your vote counts. Don't forget to use it." -- can this include a link to www.yesequality.ie

**Comment by josmas** [comment]
The screens also need some kind of navigation hint; I believe there's an arrow in the iOS version and some kind of carousel effect on windows... will look into it!

**Comment by josmas** [comment]
@canuckjacq are there any other pages with links? I have added the register page and the last one, but I seem to recall there were links to forms in the iOS app?

**Comment by canuckjacq** [comment]
These are now correct. I think they could use some styling -- a good bit more padding on the sides would be better and I think the text could be a bit smaller. 

I will also test this on a small screen device tomorrow.

**Comment by canuckjacq** [comment]
Can we make the text smaller here and add padding on the sides? At the moment, the text goes too close to the edges.

**Comment by canuckjacq** [comment]
Closing this to add new issues
