### ISSUE TITLE
It is possible to swipe the badges off the camera screen

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#15]
Can we restrict the badges to the confines of the camera display area?

**Comment by josmas** [comment]
you mean having the info pages in the same area as the camera? that's not how the iOS app looks like.
What happens to the take picture button?

It's a big structural change; with the limited time we have, I'd rather finish functionality than changing stuff that is already there.

**Comment by canuckjacq** [comment]
Hi, I think I probably worded this badly. This isn't a design change but a bug with how the Yes Equality badges work on the camera interface. I'm on slack if you want to discuss it.

**Comment by josmas** [comment]
clarification: This has nothing to do with info pages; it's the badges used within the camera view. My mistake on reading this wrong!

**Comment by canuckjacq** [comment]
This is still happening. Is it possible to restrict them to the four corners of the preview?

**Comment by Ankhwatcher** [comment]
Addressed in https://github.com/HackForEquality/android-app/commit/73c1980c9e70e952e8b573b4acdda63b3f1cf2b5 by detecting when the badge would be obscured and repositioning it onto the camera view.
