### ISSUE TITLE
App icon and splash screen need work

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#16]
The image I uploaded to the slack channel last night for the iOS submission, can that be used for the icon? Splash should be high quality like that as well. Let me know what you need and I can get a designer on it.

**Comment by josmas** [comment]
Added the image from slack for the splash screen and grabbed the launcher icons from the iOS app. It's all in #14
Can anyone review? @vladoatanasov if you have any time? thanks!
