### ISSUE TITLE
Tap to change doesn't work on first launch

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#26]
Install and launch for the first time, tap-to-change the badges isn't working. Works afterwards reliably.

**Comment by Ankhwatcher** [comment]
Fixed this in https://github.com/HackForEquality/android-app/commit/078a6248ce56f50b1a544a6aa46146fe3c5ba968 by saving the starting point of touches and checking to see if the motion event is more than one tenth of an inch from that starting point before moving the badge.
