### ISSUE TITLE
Crashes on phones without front facing camera

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#27]
I suspect crash on Young 2 is because there is no front facing camera

**Comment by Ankhwatcher** [comment]
Addressed this in https://github.com/HackForEquality/android-app/commit/020c2e69ac26186905b1eaa06680cd21731ef472 the camera will now fall back to the rear camera, and correctly open the front camera on front-only devices like the 2012 Nexus 7.
