### ISSUE TITLE
Need to implement changing badges

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#6]
iOS and Windows both do tap-to-change which is nice and elegant. Other options are fine as well at this stage, speed is pretty important.

**Comment by vladoatanasov** [comment]
I will implement it

**Comment by vladoatanasov** [comment]
Implemented, it's available in the latest merge

**Comment by canuckjacq** [comment]
On my phone, this now cycles between the white and coloured versions of a single message?

**Comment by canuckjacq** [comment]
Looks good!
