### ISSUE TITLE
Reminders screen

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#8]
Upper right hand corner of main camera screen should have a time/clock image to take the user to a reminders screen where they can switch off the local reminders that will alert the user the day before the referendum (May 21) and on the day itself (May 22nd)

**Comment by josmas** [comment]
I'm happy to work on this; will assign it to myself.
@canuckjacq do you know if they are just set Alarms in other platforms or have been written as push notifications? Alarms seems to make more sense in this case (would be simpler).

**Comment by canuckjacq** [comment]
![img_0093 1](https://cloud.githubusercontent.com/assets/11161530/7339082/9ba8cd94-ec59-11e4-8e28-235dbe926641.PNG)
I think this screen could use a change in colours so there is more contrast between the background and the switches. Similar to the iOS version (attached screenshot) would be great.

**Comment by AlanCowap** [comment]
I'll have a look at this now, but I'll stick with the Android (well Samsung anyway) style of greyed out and left-aligned when unselected; and then green and right-aligned when selected. 
Also, both reminders are showing as selected by default, so a couple of things:
1) is that what we want, it could be considered bad-form
2) From a cursory look at the code it looks like the Alarms are NOT actually set (despite appearing to be set in the Reminders fragment). So it would appear to the user as if the Alarms are set, but in fact they are not.

**Comment by AlanCowap** [comment]
Also, apols to @josmas for self-assigning this and unassigning you (I assumed it would leave both). I hope it's not bad form to do so; I'm just taking things while I'm here :)

**Comment by AlanCowap** [comment]
Ok, I've gone with Red for Alarm not activated, and Green for Alarm activated. I think that looked best from the various colours I tested with.
I also set the Alarms initial state to show the fact they are not active. I think this behaviour (not setting alarms unbeknownst to the user) is more in keeping with the Android dev philosophy of "Be a good citizen". I'll commit changes, and throw an apk to slack.

**Comment by canuckjacq** [comment]
Ok -- these used to be notifications. I'm not sure I like the "alarm" language because it doesn't give a time and might make people think they're going to be woke up because of it. Are they still notifications? And they did previously work as well. I haven't done any regression testing since, but I had put the date ahead on my phone and woke up to a notification.

**Comment by AlanCowap** [comment]
Sorry yes, the user will see a Notification.
I was saying Alarm because behind the scenes it's an Alarm event that triggers a Broadcast that causes the Notification to be sent.
The wording of the Notifcations are:
"Don't forget to vote!"
"Remind your friends to vote YES tomorrow!"
Do you want these changed e.g. "Don't forget to vote YES" or whatever.

The notifications are set for 10:30am, any preference for a different time?

**Comment by canuckjacq** [comment]
It's more the alarm confirmation text I'm worried about -- can it say "notification" is set instead of "alarm"?

I think 10:30 is very reasonable.

**Comment by AlanCowap** [comment]
@canuckjacq  Oh yeah, forgot I added the Toasts, they are to make it clear whether the Notifcation was being set on/off. I've changed Alarm to Notification. Thinking about it though, would "Reminder" be better again since it's more in keeping with the screen message.

**Comment by canuckjacq** [comment]
Agreed. Reminder is probably best.
